services:
  swagger-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: swagger-ui

    ports:
      - "${PORT}:80"

    environment:
      SWAGGER_URL: ${SWAGGER_URL}
      SWAGGER_USERNAME: ${SWAGGER_USERNAME}
      SWAGGER_PASSWORD: ${SWAGGER_PASSWORD}

      SWAGGER_SERVER: ${SWAGGER_SERVER}
      SWAGGER_SERVER_DESCRIPTION: ${SWAGGER_SERVER_DESCRIPTION}

    restart: unless-stopped